domain: feli.gg       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://feli.gg  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: feli.gg/test/      # place folder name if the site is served in a subfolder

# Site settings
title: Feli.gg
description: Programmer and occasional streamer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: FeliGoblin
user_description: Programmer and occasional streamer
user_title: Programmer
email: mail.feli.gg
twitter_username: FeliGoblin
#instagram_username:
#facebook_username:
#linkedin_username:
github_username: FeliGoblin
youtube_at: FeliGoblin
discord_invite: nFYHZPu
# medium_username:
# medium_url:
# gplus_username:
kofi_username: FeliGoblin

exclude: ['package.json', 'src', 'node_modules', 'vendor']

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - "package*.json"

plugins:
    - jekyll-minifier

jekyll-minifier:
  remove_comments: true             # Default: true
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
