domain: feli.gg       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://feli.gg  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""      # place folder name if the site is served in a subfolder
repository: FeliGoblin/feli.gg

# Site settings
title: Feli.gg
prefix: FELI
typing_text_1: "&nbsp;GOBLIN"
typing_text_2: .GG

# User settings
username: FeliGoblin
user_description: Programmer and occasional streamer
user_title: Programmer
email: mail.feli.gg
twitter_username: FeliGoblin
github_username: FeliGoblin
youtube_at: FeliGoblin
discord_invite: nFYHZPu
kofi_username: FeliGoblin

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
